/**
 * T4.173 — Canonical breed catalog for species-filtered Autocomplete inputs.
 * 62 Canine + 33 Feline = 95 total entries.
 * Sorted alphabetically per species. Sentinels (Mixed Breed, Other) at end.
 * freeSolo on admin Autocomplete allows custom entry for breeds not in this list.
 */
export const BREED_CATALOG = {
  Canine: [
    'Afghan Hound',
    'Akita',
    'Alaskan Malamute',
    'American Bully',
    'American Pit Bull Terrier',
    'Aspin (Asong Pinoy)',
    'Australian Shepherd',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Belgian Malinois',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Border Collie',
    'Boston Terrier',
    'Boxer',
    'Brussels Griffon',
    'Bulldog',
    'Cavalier King Charles Spaniel',
    'Chihuahua',
    'Chow Chow',
    'Cocker Spaniel',
    'Corgi (Pembroke Welsh)',
    'Dachshund',
    'Dalmatian',
    'Doberman Pinscher',
    'English Springer Spaniel',
    'French Bulldog',
    'German Shepherd',
    'Golden Retriever',
    'Great Dane',
    'Greyhound',
    'Havanese',
    'Irish Setter',
    'Italian Greyhound',
    'Jack Russell Terrier',
    'Japanese Chin',
    'Japanese Spitz',
    'Labrador Retriever',
    'Lhasa Apso',
    'Maltese',
    'Mastiff',
    'Miniature Pinscher',
    'Miniature Schnauzer',
    'Newfoundland',
    'Papillon',
    'Pekingese',
    'Pomeranian',
    'Poodle (Standard)',
    'Poodle (Toy / Miniature)',
    'Pug',
    'Rhodesian Ridgeback',
    'Rottweiler',
    'Saint Bernard',
    'Samoyed',
    'Shar-Pei',
    'Shetland Sheepdog',
    'Shiba Inu',
    'Shih Tzu',
    'Siberian Husky',
    // --- Sentinels (always last, in this order) ---
    'Mixed Breed',
    'Other',
  ],
  Feline: [
    'Abyssinian',
    'American Shorthair',
    'Bengal',
    'Birman',
    'Bombay',
    'British Longhair',
    'British Shorthair',
    'Burmese',
    'Calico (Pattern)',
    'Devon Rex',
    'Egyptian Mau',
    'Exotic Shorthair',
    'Havana Brown',
    'Himalayan',
    'Japanese Bobtail',
    'Maine Coon',
    'Manx',
    'Munchkin',
    'Norwegian Forest Cat',
    'Ocicat',
    'Oriental Shorthair',
    'Persian',
    'Puspin (Pusang Pinoy)',
    'Ragdoll',
    'Russian Blue',
    'Scottish Fold',
    'Siamese',
    'Singapura',
    'Snowshoe',
    'Sphynx',
    'Tabby (Pattern)',
    // --- Sentinels ---
    'Mixed Breed',
    'Other',
  ],
};
