/**
 * diagnosisConstants.js
 * T4.141 — Structured Diagnosis System (Day 1)
 *
 * Single source of truth for the veterinary diagnosis catalog.
 * ~500+ conditions across 13 categories, severity scale definitions,
 * and the category list — mirrors the labTestConstants.js architecture.
 *
 * hasSeverity: true ONLY for conditions with established, published
 * clinical grading systems (IRIS CKD, AVDC Periodontal, cardiac murmur
 * grading, BCS, WHOTNM, Patnaik mast cell, VCOG soft-tissue sarcoma).
 * Do NOT set hasSeverity:true on conditions lacking a standard scale.
 *
 * ID format: {category-prefix}-{kebab-name}
 * Species: ['dog','cat'] for universal; ['dog'] or ['cat'] for species-specific.
 */

// ─── Categories ──────────────────────────────────────────────────────────────

export const DIAGNOSIS_CATEGORIES = [
  'Dermatology',
  'Gastrointestinal',
  'Renal / Urinary',
  'Dental',
  'Musculoskeletal',
  'Respiratory',
  'Cardiac',
  'Endocrine',
  'Infectious',
  'Oncology',
  'Ophthalmology',
  'Behavioral',
  'Preventive / Wellness',
];

// ─── Severity / Staging Scales ────────────────────────────────────────────────

/**
 * Map of scale IDs to their { value, label } option arrays.
 * value is stored in the medical_record; label is shown in the UI.
 */
export const SEVERITY_SCALES = {
  /** AVDC Periodontal Disease Grading — 4 stages */
  'dental-1-4': [
    { value: 'Grade 1', label: 'Grade 1 — Gingivitis only, no attachment loss' },
    { value: 'Grade 2', label: 'Grade 2 — Early periodontitis, <25% attachment loss' },
    { value: 'Grade 3', label: 'Grade 3 — Moderate periodontitis, 25–50% attachment loss' },
    { value: 'Grade 4', label: 'Grade 4 — Advanced periodontitis, >50% attachment loss' },
  ],

  /** IRIS CKD Staging — 4 stages */
  'renal-I-IV': [
    { value: 'Stage I',   label: 'Stage I — Non-azotemic, at risk' },
    { value: 'Stage II',  label: 'Stage II — Mild azotemia (creatinine 1.6–2.8 mg/dL canine / 1.6–2.8 feline)' },
    { value: 'Stage III', label: 'Stage III — Moderate azotemia (creatinine 2.9–5.0 mg/dL)' },
    { value: 'Stage IV',  label: 'Stage IV — Severe azotemia (creatinine >5.0 mg/dL)' },
  ],

  /** Cardiac murmur auscultation grading — 6 grades */
  'murmur-1-6': [
    { value: 'Grade I/VI',   label: 'Grade I/VI — Barely audible, single location' },
    { value: 'Grade II/VI',  label: 'Grade II/VI — Soft, easily heard' },
    { value: 'Grade III/VI', label: 'Grade III/VI — Moderate, no palpable thrill' },
    { value: 'Grade IV/VI',  label: 'Grade IV/VI — Loud, palpable thrill present' },
    { value: 'Grade V/VI',   label: 'Grade V/VI — Very loud, heard with stethoscope at edge of chest' },
    { value: 'Grade VI/VI',  label: 'Grade VI/VI — Heard without stethoscope contact' },
  ],

  /** Body Condition Score — 9-point scale */
  'bcs-1-9': [
    { value: '1/9', label: '1/9 — Emaciated' },
    { value: '2/9', label: '2/9 — Very thin' },
    { value: '3/9', label: '3/9 — Thin' },
    { value: '4/9', label: '4/9 — Underweight' },
    { value: '5/9', label: '5/9 — Ideal' },
    { value: '6/9', label: '6/9 — Slightly overweight' },
    { value: '7/9', label: '7/9 — Overweight' },
    { value: '8/9', label: '8/9 — Obese' },
    { value: '9/9', label: '9/9 — Grossly obese' },
  ],

  /** Simplified clinical TNM staging (oncology) */
  'tnm': [
    { value: 'Stage I',   label: 'Stage I — Localized, no nodal/distant spread' },
    { value: 'Stage II',  label: 'Stage II — Locally invasive or regional nodes' },
    { value: 'Stage III', label: 'Stage III — Regional lymph node metastasis' },
    { value: 'Stage IV',  label: 'Stage IV — Distant metastasis' },
  ],

  /** Generic 5-point severity scale */
  'severity-1-5': [
    { value: 'Mild',             label: 'Mild' },
    { value: 'Moderate',         label: 'Moderate' },
    { value: 'Moderate-Severe',  label: 'Moderate-Severe' },
    { value: 'Severe',           label: 'Severe' },
    { value: 'Critical',         label: 'Critical' },
  ],

  /** Patnaik/WHO 3-point histologic grade (mast cell tumors, soft-tissue sarcomas) */
  'grade-1-3': [
    { value: 'Grade I',   label: 'Grade I — Well differentiated, low mitotic index' },
    { value: 'Grade II',  label: 'Grade II — Moderately differentiated' },
    { value: 'Grade III', label: 'Grade III — Poorly differentiated, high mitotic index' },
  ],

  /** Generic 5-stage disease progression scale */
  'stage-1-5': [
    { value: 'Stage 1', label: 'Stage 1' },
    { value: 'Stage 2', label: 'Stage 2' },
    { value: 'Stage 3', label: 'Stage 3' },
    { value: 'Stage 4', label: 'Stage 4' },
    { value: 'Stage 5', label: 'Stage 5' },
  ],

  /** ACVIM consensus staging for canine myxomatous mitral valve disease */
  'mvd-acvim': [
    { value: 'Stage A',  label: 'Stage A — At risk, no structural change' },
    { value: 'Stage B1', label: 'Stage B1 — Preclinical, no cardiomegaly' },
    { value: 'Stage B2', label: 'Stage B2 — Preclinical, cardiomegaly present' },
    { value: 'Stage C',  label: 'Stage C — Current or prior CHF signs' },
    { value: 'Stage D',  label: 'Stage D — Refractory to standard therapy' },
  ],

  /** Acute vs Chronic classification */
  'acute-chronic': [
    { value: 'Acute',   label: 'Acute' },
    { value: 'Chronic', label: 'Chronic' },
  ],
};

// ─── Default Diagnosis Catalog ─────────────────────────────────────────────

/**
 * ~500+ veterinary diagnoses across 13 categories.
 * Organized by category, then alphabetically by name within each category.
 */
export const DEFAULT_DIAGNOSIS_CATALOG = [

  // ─── DERMATOLOGY (~45) ─────────────────────────────────────────────────────
  { id: 'derm-abscess-skin',          name: 'Abscess (Skin)',                        category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-acral-lick',            name: 'Acral Lick Dermatitis',                 category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-alopecia-pattern',      name: 'Alopecia (Pattern / Endocrine)',        category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-angioedema',            name: 'Angioedema',                            category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-atopy',                 name: 'Atopic Dermatitis (Atopy)',             category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-burns',                 name: 'Burns (Thermal / Chemical)',            category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-callus',                name: 'Callus',                                category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-cheyletiella',          name: 'Cheyletiella (Fur Mite)',               category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-chin-acne-feline',      name: 'Chin Acne (Feline)',                   category: 'Dermatology',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'derm-color-dilution-alop',   name: 'Color Dilution Alopecia',              category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-contact-dermatitis',    name: 'Contact Dermatitis',                   category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-cutaneous-horn',        name: 'Cutaneous Horn',                       category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-demodex',               name: 'Demodicosis (Demodex Mange)',           category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-dermoid-sinus',         name: 'Dermoid Sinus',                        category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-drug-eruption',         name: 'Drug Eruption',                        category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-ear-hematoma',          name: 'Ear Hematoma (Aural)',                 category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-egc',                   name: 'Eosinophilic Granuloma Complex',        category: 'Dermatology',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'derm-epidermal-cyst',        name: 'Epidermal / Follicular Cyst',          category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-fad',                   name: 'Flea Allergy Dermatitis',              category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-feline-miliary',        name: 'Feline Miliary Dermatitis',            category: 'Dermatology',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'derm-fly-strike',            name: 'Fly Strike (Myiasis)',                 category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-follicular-dysplasia',  name: 'Follicular Dysplasia',                 category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-food-allergy',          name: 'Food Allergy / Cutaneous Adverse Reaction', category: 'Dermatology',   species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-histiocytoma',          name: 'Histiocytoma (Cutaneous)',             category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-hot-spot',              name: 'Hot Spot (Acute Moist Dermatitis)',    category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-interdigital-cyst',     name: 'Interdigital Cyst / Furunculosis',     category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-laceration-wound',      name: 'Laceration / Bite Wound',             category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-lipoma',                name: 'Lipoma (Subcutaneous)',                category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-lick-granuloma',        name: 'Lick Granuloma',                      category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-lupoid-onycho',         name: 'Lupoid Onychodystrophy',              category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-malassezia',            name: 'Malassezia Dermatitis (Yeast)',        category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-otitis-externa',        name: 'Otitis Externa',                      category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-otitis-media',          name: 'Otitis Media',                        category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-otitis-interna',        name: 'Otitis Interna',                      category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-pemphigus',             name: 'Pemphigus Foliaceus / Complex',        category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-pyoderma-superficial',  name: 'Pyoderma (Superficial)',              category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-pyoderma-deep',         name: 'Pyoderma (Deep)',                     category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-ringworm',              name: 'Ringworm (Dermatophytosis)',           category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-sarcoptic-mange',       name: 'Sarcoptic Mange (Scabies)',           category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-sebaceous-adenitis',    name: 'Sebaceous Adenitis',                  category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'derm-seborrhea',             name: 'Seborrhea (Primary / Secondary)',      category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-solar-dermatitis',      name: 'Solar Dermatitis',                    category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-skin-tag',              name: 'Skin Tag (Fibroepithelial Polyp)',     category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-tick-infestation',      name: 'Tick Infestation',                    category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-urticaria',             name: 'Urticaria (Hives)',                   category: 'Dermatology',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'derm-zinc-responsive',       name: 'Zinc-Responsive Dermatosis',          category: 'Dermatology',         species: ['dog'],        hasSeverity: false, severityScale: null },

  // ─── GASTROINTESTINAL (~50) ────────────────────────────────────────────────
  { id: 'gi-anal-gland',              name: 'Anal Gland Impaction / Abscess',       category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-bile-duct-obstruct',      name: 'Bile Duct Obstruction',               category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-cholangiohepatitis',      name: 'Cholangiohepatitis',                  category: 'Gastrointestinal',    species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'gi-coccidia',                name: 'Coccidiosis',                          category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-colitis-acute',           name: 'Colitis (Acute)',                      category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-colitis-chronic',         name: 'Colitis (Chronic)',                    category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-colorectal-carcinoma',    name: 'Colorectal Carcinoma',                category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-constipation',            name: 'Constipation / Obstipation',          category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-dietary-indiscretion',    name: 'Dietary Indiscretion',               category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-epi',                     name: 'Exocrine Pancreatic Insufficiency (EPI)', category: 'Gastrointestinal', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-esophageal-fb',           name: 'Esophageal Foreign Body',             category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-esophagitis',             name: 'Esophagitis',                          category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-food-intolerance',        name: 'Food Intolerance',                    category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-gallbladder-mucocele',    name: 'Gallbladder Mucocele',                category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-gastric-carcinoma',       name: 'Gastric Carcinoma',                   category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-gastric-motility',        name: 'Gastric Motility Disorder',           category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-gastric-ulcer',           name: 'Gastric Ulcer',                       category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-gastritis-acute',         name: 'Gastritis (Acute)',                   category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-gastritis-chronic',       name: 'Gastritis (Chronic)',                 category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-gdv',                     name: 'Gastric Dilatation-Volvulus (GDV)',   category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-giardia',                 name: 'Giardiasis',                          category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-hge',                     name: 'Hemorrhagic Gastroenteritis (HGE/AHDS)', category: 'Gastrointestinal', species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-hepatic-lipidosis',       name: 'Hepatic Lipidosis',                   category: 'Gastrointestinal',    species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'gi-hepatitis-chronic',       name: 'Hepatitis (Chronic)',                 category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-histoplasmosis-gi',       name: 'Histoplasmosis (GI)',                 category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-ibd',                     name: 'Inflammatory Bowel Disease (IBD)',     category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-intestinal-fb',           name: 'Intestinal Foreign Body',             category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-intestinal-parasites',    name: 'Intestinal Parasites (Roundworm / Hookworm / Whipworm / Tapeworm)', category: 'Gastrointestinal', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-intussusception',         name: 'Intussusception',                     category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-leiomyoma',               name: 'Leiomyoma / Leiomyosarcoma',          category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-lymphangiectasia',        name: 'Lymphangiectasia (Intestinal)',        category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-lpe',                     name: 'Lymphocytic-Plasmacytic Enteritis',   category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-megacolon',               name: 'Megacolon',                           category: 'Gastrointestinal',    species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'gi-megaesophagus',           name: 'Megaesophagus',                       category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-mesenteric-torsion',      name: 'Mesenteric Torsion',                  category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-pancreatitis-acute',      name: 'Pancreatitis (Acute)',                category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-pancreatitis-chronic',    name: 'Pancreatitis (Chronic)',              category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-parvo',                   name: 'Parvoviral Enteritis',                category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-perianal-fistula',        name: 'Perianal Fistula',                    category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-portosystemic-shunt',     name: 'Portosystemic Shunt',                category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-protein-losing-entero',   name: 'Protein-Losing Enteropathy',         category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-pyloric-stenosis',        name: 'Pyloric Stenosis',                    category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-pythiosis',               name: 'Pythiosis (GI)',                       category: 'Gastrointestinal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'gi-rectal-polyp',            name: 'Rectal Polyp',                        category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-rectal-prolapse',         name: 'Rectal Prolapse',                     category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-si-lymphoma',             name: 'Small Intestinal Lymphoma',           category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-toxin-ingestion',         name: 'Toxin Ingestion',                     category: 'Gastrointestinal',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'gi-tritrichomonas',          name: 'Tritrichomonas blagburni',            category: 'Gastrointestinal',    species: ['cat'],        hasSeverity: false, severityScale: null },

  // ─── RENAL / URINARY (~35) ────────────────────────────────────────────────
  { id: 'renal-aki',                  name: 'Acute Kidney Injury (AKI)',            category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-amyloidosis',          name: 'Renal Amyloidosis',                   category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-bladder-atony',        name: 'Bladder Atony',                       category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-bladder-polyp',        name: 'Bladder Polyp',                       category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-bladder-tcc',          name: 'Transitional Cell Carcinoma (Bladder)', category: 'Renal / Urinary',   species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-ckd',                  name: 'Chronic Kidney Disease (CKD)',         category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'renal-I-IV' },
  { id: 'renal-ectopic-ureter',       name: 'Ectopic Ureter',                      category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-eg-toxicosis',         name: 'Ethylene Glycol Toxicosis',           category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-fanconi',              name: 'Fanconi Syndrome',                    category: 'Renal / Urinary',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'renal-flutd',                name: 'Feline Lower Urinary Tract Disease (FLUTD)', category: 'Renal / Urinary', species: ['cat'],    hasSeverity: false, severityScale: null },
  { id: 'renal-glomerulonephritis',   name: 'Glomerulonephritis',                  category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-hydronephrosis',       name: 'Hydronephrosis',                      category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-idiopathic-cystitis',  name: 'Idiopathic Cystitis',                category: 'Renal / Urinary',     species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'renal-lily-nephrotox',       name: 'Lily Nephrotoxicosis',                category: 'Renal / Urinary',     species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'renal-lymphoma-renal',       name: 'Renal Lymphoma',                      category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-nephrolithiasis',      name: 'Nephrolithiasis (Kidney Stones)',     category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-ndi',                  name: 'Nephrogenic Diabetes Insipidus',      category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-nsaid-nephrotox',      name: 'NSAID Nephrotoxicosis',               category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-patent-urachus',       name: 'Patent Urachus',                      category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-perinephric-cyst',     name: 'Perinephric Pseudocyst',              category: 'Renal / Urinary',     species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'renal-pkd',                  name: 'Polycystic Kidney Disease (PKD)',      category: 'Renal / Urinary',     species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'renal-pln',                  name: 'Protein-Losing Nephropathy',          category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-pyelonephritis',       name: 'Pyelonephritis',                      category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-renal-carcinoma',      name: 'Renal Carcinoma',                     category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-renal-dysplasia',      name: 'Renal Dysplasia',                     category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-reflex-dyssynergia',   name: 'Reflex Dyssynergia',                  category: 'Renal / Urinary',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'renal-rta',                  name: 'Renal Tubular Acidosis',              category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-urethral-obstruction', name: 'Urethral Obstruction',                category: 'Renal / Urinary',     species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'renal-urethral-prolapse',    name: 'Urethral Prolapse',                   category: 'Renal / Urinary',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'renal-urethral-stricture',   name: 'Urethral Stricture',                  category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-ureteral-obstruct',    name: 'Ureteral Obstruction',                category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-urinary-incont',       name: 'Urinary Incontinence (Sphincter / Neurogenic)', category: 'Renal / Urinary', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-urolithiasis',         name: 'Urolithiasis (Struvite / Oxalate / Urate / Cystine)', category: 'Renal / Urinary', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-uti',                  name: 'Urinary Tract Infection (UTI)',        category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'renal-vesicourachal-div',    name: 'Vesicourachal Diverticulum',          category: 'Renal / Urinary',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── DENTAL (~30) ─────────────────────────────────────────────────────────
  { id: 'dental-cleft-palate',        name: 'Cleft Palate',                        category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-cmo',                 name: 'Craniomandibular Osteopathy',         category: 'Dental',              species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'dental-dentigerous-cyst',    name: 'Dentigerous Cyst',                    category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-enamel-hypoplasia',   name: 'Enamel Hypoplasia',                   category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-epulis',              name: 'Epulis / Peripheral Odontogenic Fibroma', category: 'Dental',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-fcgs',                name: 'Feline Chronic Gingivostomatitis',     category: 'Dental',              species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'dental-fibrosarcoma-oral',   name: 'Fibrosarcoma (Oral)',                 category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-forl',                name: 'Feline Tooth Resorption (FORL/TR)',   category: 'Dental',              species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'dental-gingivitis',          name: 'Gingivitis',                           category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-lingual-ulcer',       name: 'Lingual Ulcer',                       category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-lip-fold',            name: 'Lip Fold Dermatitis',                 category: 'Dental',              species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'dental-malocclusion',        name: 'Malocclusion (Class I / II / III)',   category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-mandibular-fx',       name: 'Mandibular Fracture',                 category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-masticatory-mm',      name: 'Masticatory Muscle Myositis',         category: 'Dental',              species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'dental-melanoma-oral',       name: 'Oral Melanoma',                       category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-oral-mass',           name: 'Oral Mass (Unspecified)',              category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-oral-papilloma',      name: 'Oral Papillomatosis',                 category: 'Dental',              species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'dental-oronasal-fistula',    name: 'Oronasal Fistula',                    category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-perio',               name: 'Periodontal Disease',                 category: 'Dental',              species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'dental-1-4' },
  { id: 'dental-ranula',              name: 'Salivary Mucocele / Ranula',          category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-retained-deciduous',  name: 'Retained Deciduous Teeth',            category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-scc-oral',            name: 'Squamous Cell Carcinoma (Oral)',       category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-stomatitis',          name: 'Stomatitis (Lymphocytic-Plasmacytic)', category: 'Dental',             species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'dental-supernumerary-teeth', name: 'Supernumerary Teeth',                 category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-tmj-luxation',        name: 'Temporomandibular Joint (TMJ) Luxation', category: 'Dental',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-tongue-fb',           name: 'Tongue Foreign Body',                 category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-tooth-attrition',     name: 'Tooth Wear / Attrition',             category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-tooth-fracture',      name: 'Tooth Fracture (Uncomplicated / Complicated)', category: 'Dental',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-tooth-root-abscess',  name: 'Tooth Root Abscess',                 category: 'Dental',              species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'dental-zygomatic-sialocele', name: 'Zygomatic Gland Sialocele',          category: 'Dental',              species: ['dog'],        hasSeverity: false, severityScale: null },

  // ─── MUSCULOSKELETAL (~40) ────────────────────────────────────────────────
  { id: 'msk-achilles-rupture',       name: 'Achilles Tendon Rupture',             category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-atlantoaxial',           name: 'Atlantoaxial Instability',            category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-biceps-tenosynovitis',   name: 'Biceps Tenosynovitis',               category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-carpal-hyperext',        name: 'Carpal Hyperextension',               category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-ccl',                    name: 'Cranial Cruciate Ligament Rupture (CCL)', category: 'Musculoskeletal', species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-cervical-spondylomyelo', name: 'Cervical Spondylomyelopathy (Wobbler)', category: 'Musculoskeletal', species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-chondrosarcoma',         name: 'Chondrosarcoma',                      category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-degen-myelopathy',       name: 'Degenerative Myelopathy',             category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-diskospondylitis',       name: 'Diskospondylitis',                    category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-elbow-dysplasia',        name: 'Elbow Dysplasia',                     category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-fce',                    name: 'Fibrocartilaginous Embolism (FCE)',   category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-fibrotic-myopathy',      name: 'Fibrotic Myopathy',                  category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-fibrosarcoma-bone',      name: 'Fibrosarcoma (Bone)',                 category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-fracture',               name: 'Fracture (Femur / Tibia / Radius-Ulna / Pelvis / Vertebral)', category: 'Musculoskeletal', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-gracilis-contracture',   name: 'Gracilis Contracture',               category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-hip-dysplasia',          name: 'Hip Dysplasia',                       category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-hod',                    name: 'Hypertrophic Osteodystrophy (HOD)',   category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-ivdd',                   name: 'Intervertebral Disc Disease (IVDD)',  category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-lcpd',                   name: 'Legg-Calvé-Perthes Disease',          category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-lumbosacral-stenosis',   name: 'Lumbosacral Stenosis (Cauda Equina)', category: 'Musculoskeletal',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-luxation',               name: 'Joint Luxation (Hip / Shoulder / Elbow)', category: 'Musculoskeletal', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-medial-shoulder',        name: 'Medial Shoulder Instability',         category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-muscle-strain',          name: 'Muscle Strain / Sprain',             category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-myasthenia-gravis',      name: 'Myasthenia Gravis',                  category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-nshu-hyper-osteo',       name: 'Nutritional Secondary Hyperparathyroidism', category: 'Musculoskeletal', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-ocd',                    name: 'Osteochondritis Dissecans (OCD)',     category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-osteoarthritis',         name: 'Osteoarthritis / Degenerative Joint Disease', category: 'Musculoskeletal', species: ['dog', 'cat'], hasSeverity: true, severityScale: 'severity-1-5' },
  { id: 'msk-osteomyelitis',          name: 'Osteomyelitis',                       category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-osteosarcoma',           name: 'Osteosarcoma',                        category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-panosteitis',            name: 'Panosteitis',                         category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-patellar-luxation',      name: 'Patellar Luxation',                   category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-plantar-lig',            name: 'Plantar Ligament Injury',             category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-polyarthritis-imm',      name: 'Immune-Mediated Polyarthritis',       category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-polymyositis',           name: 'Polymyositis',                        category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-septic-arthritis',       name: 'Septic Arthritis',                    category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-spinal-cord-injury',     name: 'Spinal Cord Injury',                  category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-supraspinatus-tend',     name: 'Supraspinatus Tendinopathy',          category: 'Musculoskeletal',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'msk-synovial-sarcoma',       name: 'Synovial Cell Sarcoma',               category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'msk-tmj-dysplasia',          name: 'Temporomandibular Joint Dysplasia',   category: 'Musculoskeletal',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── RESPIRATORY (~35) ────────────────────────────────────────────────────
  { id: 'resp-aspergillosis-nasal',   name: 'Aspergillosis (Nasal / Systemic)',    category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-asthma-feline',         name: 'Feline Asthma',                       category: 'Respiratory',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'resp-blastomycosis',         name: 'Blastomycosis (Pulmonary)',            category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-boas',                  name: 'Brachycephalic Obstructive Airway Syndrome (BOAS)', category: 'Respiratory', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-bronchiectasis',        name: 'Bronchiectasis',                       category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-chronic-bronchitis',    name: 'Chronic Bronchitis',                  category: 'Respiratory',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-chylothorax',           name: 'Chylothorax',                          category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-coccidioido',           name: 'Coccidioidomycosis (Pulmonary)',       category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-diaphragmatic-hernia',  name: 'Diaphragmatic Hernia',                category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-epiglottic-retrover',   name: 'Epiglottic Retroversion',             category: 'Respiratory',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-epistaxis',             name: 'Epistaxis',                            category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-itb',                   name: 'Infectious Tracheobronchitis (Kennel Cough)', category: 'Respiratory',  species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-laryngeal-paralysis',   name: 'Laryngeal Paralysis',                 category: 'Respiratory',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-lung-lobe-torsion',     name: 'Lung Lobe Torsion',                   category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-lungworm',              name: 'Lungworm (Aelurostrongylus / Angiostrongylus)', category: 'Respiratory', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-mesothelioma',          name: 'Mesothelioma',                         category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-nasal-fb',              name: 'Nasal Foreign Body',                  category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-nasal-tumor',           name: 'Nasal Tumor (Adenocarcinoma / Lymphoma)', category: 'Respiratory',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-nasopharyngeal-polyp',  name: 'Nasopharyngeal Polyp',                category: 'Respiratory',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'resp-nasopharyngeal-stenosis', name: 'Nasopharyngeal Stenosis',           category: 'Respiratory',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'resp-pcd',                   name: 'Primary Ciliary Dyskinesia',           category: 'Respiratory',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-pleural-effusion',      name: 'Pleural Effusion',                    category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pneumonia',             name: 'Pneumonia (Bacterial / Aspiration / Viral / Fungal)', category: 'Respiratory', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pneumothorax',          name: 'Pneumothorax',                         category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-ppdh',                  name: 'Peritoneopericardial Diaphragmatic Hernia (PPDH)', category: 'Respiratory', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pulmonary-contusion',   name: 'Pulmonary Contusion',                 category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pulmonary-edema',       name: 'Pulmonary Edema (Cardiogenic / Non-Cardiogenic)', category: 'Respiratory', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pulmonary-fibrosis',    name: 'Pulmonary Fibrosis',                  category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pte',                   name: 'Pulmonary Thromboembolism',            category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-pyothorax',             name: 'Pyothorax',                            category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-rhinitis-sinusitis',    name: 'Chronic Rhinitis / Sinusitis',        category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-reverse-sneezing',      name: 'Reverse Sneezing (Paroxysmal Respiration)', category: 'Respiratory',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-tracheal-collapse',     name: 'Tracheal Collapse',                   category: 'Respiratory',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'resp-tracheal-fb',           name: 'Tracheal Foreign Body',               category: 'Respiratory',         species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'resp-uri-feline',            name: 'Feline Upper Respiratory Infection (URI)', category: 'Respiratory',    species: ['cat'],        hasSeverity: false, severityScale: null },

  // ─── CARDIAC (~30) ────────────────────────────────────────────────────────
  { id: 'card-arvc',                  name: 'Arrhythmogenic Right Ventricular Cardiomyopathy (ARVC)', category: 'Cardiac', species: ['dog'],  hasSeverity: false, severityScale: null },
  { id: 'card-asd',                   name: 'Atrial Septal Defect (ASD)',           category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-atrial-fib',            name: 'Atrial Fibrillation',                 category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-ate',                   name: 'Aortic Thromboembolism / Saddle Thrombus', category: 'Cardiac',         species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'card-av-block',              name: 'Atrioventricular Block (1st / 2nd / 3rd Degree)', category: 'Cardiac',  species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-chemodectoma',          name: 'Chemodectoma (Heart Base Tumor)',      category: 'Cardiac',             species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'card-chf',                   name: 'Congestive Heart Failure (CHF)',       category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-dcm',                   name: 'Dilated Cardiomyopathy (DCM)',         category: 'Cardiac',             species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'card-endocarditis',          name: 'Infective Endocarditis',              category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-heartworm',             name: 'Heartworm Disease (Dirofilariasis)',   category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-hemangiosarcoma',       name: 'Hemangiosarcoma (Cardiac)',            category: 'Cardiac',             species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'card-hcm',                   name: 'Hypertrophic Cardiomyopathy (HCM)',   category: 'Cardiac',             species: ['cat'],        hasSeverity: true,  severityScale: 'severity-1-5' },
  { id: 'card-murmur-functional',     name: 'Heart Murmur (Functional / Innocent)', category: 'Cardiac',            species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'murmur-1-6' },
  { id: 'card-mvd',                   name: 'Mitral Valve Disease (MVD / MMVD)',   category: 'Cardiac',             species: ['dog'],        hasSeverity: true,  severityScale: 'mvd-acvim' },
  { id: 'card-myocarditis',           name: 'Myocarditis',                         category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-pda',                   name: 'Patent Ductus Arteriosus (PDA)',       category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-pericardial-effusion',  name: 'Pericardial Effusion',                category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-pulmonary-htn',         name: 'Pulmonary Hypertension',              category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-pulmonic-stenosis',     name: 'Pulmonic Stenosis',                   category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-rcm',                   name: 'Restrictive Cardiomyopathy',          category: 'Cardiac',             species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'card-sick-sinus',            name: 'Sick Sinus Syndrome',                 category: 'Cardiac',             species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'card-subaortic-stenosis',    name: 'Subaortic Stenosis',                  category: 'Cardiac',             species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'card-svt',                   name: 'Supraventricular Tachycardia',         category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-systemic-htn',          name: 'Systemic Hypertension',               category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-cardiac-tamponade',     name: 'Cardiac Tamponade',                   category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-tetralogy',             name: 'Tetralogy of Fallot',                 category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-tricuspid-dysplasia',   name: 'Tricuspid Valve Dysplasia',           category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-vpc',                   name: 'Ventricular Premature Complexes (VPC)', category: 'Cardiac',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-vsd',                   name: 'Ventricular Septal Defect (VSD)',      category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'card-vtach',                 name: 'Ventricular Tachycardia',              category: 'Cardiac',             species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── ENDOCRINE (~30) ──────────────────────────────────────────────────────
  { id: 'endo-acromegaly',            name: 'Acromegaly',                          category: 'Endocrine',           species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'endo-adrenal-incidental',    name: 'Adrenal Incidentaloma',               category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-adrenal-tumor',         name: 'Adrenal Tumor (Adenoma / Carcinoma)', category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-addisons',              name: 'Hypoadrenocorticism (Addison Disease)', category: 'Endocrine',         species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-alopecia-x',            name: 'Alopecia X',                          category: 'Endocrine',           species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-cushings',              name: 'Hyperadrenocorticism (Cushing Disease)', category: 'Endocrine',        species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-diabetes-mellitus',     name: 'Diabetes Mellitus',                   category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-diabetes-insipidus',    name: 'Diabetes Insipidus (Central / Nephrogenic)', category: 'Endocrine',   species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-dka',                   name: 'Diabetic Ketoacidosis (DKA)',          category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-epi-endo',              name: 'Exocrine Pancreatic Insufficiency (Endocrine)', category: 'Endocrine',  species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-feline-sym-alopecia',   name: 'Feline Symmetric Alopecia',           category: 'Endocrine',           species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'endo-gh-responsive',         name: 'Growth Hormone-Responsive Dermatosis', category: 'Endocrine',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-hyperaldosteronism',    name: 'Hyperaldosteronism (Conn Syndrome)',  category: 'Endocrine',           species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'endo-hyperestrinism',        name: 'Hyperestrinism',                       category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-hyperparathyroidism',   name: 'Hyperparathyroidism (Primary / Secondary)', category: 'Endocrine',    species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-hyperthyroidism',       name: 'Hyperthyroidism',                      category: 'Endocrine',           species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'endo-hypoparathyroidism',    name: 'Hypoparathyroidism',                   category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-hypothyroidism',        name: 'Hypothyroidism',                       category: 'Endocrine',           species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-insulinoma',            name: 'Insulinoma',                           category: 'Endocrine',           species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-iodine-deficiency',     name: 'Iodine Deficiency',                   category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-metabolic-syndrome',    name: 'Metabolic Syndrome',                  category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-nonthyroidal-illness',  name: 'Nonthyroidal Illness Syndrome (Euthyroid Sick)', category: 'Endocrine', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-obesity',               name: 'Obesity',                              category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'bcs-1-9' },
  { id: 'endo-ovarian-remnant',       name: 'Ovarian Remnant Syndrome',            category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-pancreatic-tumor',      name: 'Pancreatic Tumor (Adenocarcinoma)',   category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-pheochromocytoma',      name: 'Pheochromocytoma',                    category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-sex-hormone-alopecia',  name: 'Sex Hormone Alopecia',                category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-sertoli-cell',          name: 'Sertoli Cell Tumor',                  category: 'Endocrine',           species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'endo-thyroid-carcinoma',     name: 'Thyroid Carcinoma',                   category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'endo-thyroid-dysgenesis',    name: 'Thyroid Dysgenesis',                  category: 'Endocrine',           species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── INFECTIOUS (~45) ─────────────────────────────────────────────────────
  { id: 'inf-actinomycosis',          name: 'Actinomycosis',                        category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-anaplasmosis',           name: 'Anaplasmosis',                         category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-aspergillosis',          name: 'Aspergillosis (Systemic)',              category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-babesiosis',             name: 'Babesiosis',                           category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-bartonellosis',          name: 'Bartonellosis (Cat Scratch Fever)',    category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-blastomycosis',          name: 'Blastomycosis (Systemic)',             category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-bordetella',             name: 'Bordetella (Kennel Cough)',            category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-botulism',               name: 'Botulism',                             category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-campylobacteriosis',     name: 'Campylobacteriosis',                   category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-canine-coronavirus',     name: 'Canine Coronavirus',                  category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-canine-distemper',       name: 'Canine Distemper',                    category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-canine-hepatitis',       name: 'Canine Infectious Hepatitis (Adenovirus)', category: 'Infectious',     species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-canine-influenza',       name: 'Canine Influenza',                    category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-clostridial-enteritis',  name: 'Clostridial Enteritis',               category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-cryptococcosis',         name: 'Cryptococcosis',                       category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-ehrlichiosis',           name: 'Ehrlichiosis (Ehrlichia canis)',       category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-felv',                   name: 'Feline Leukemia Virus (FeLV)',         category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-feline-calicivirus',     name: 'Feline Calicivirus',                  category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-feline-coronavirus',     name: 'Feline Coronavirus',                  category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-feline-herpesvirus',     name: 'Feline Herpesvirus (FHV-1)',          category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-feline-panleukopenia',   name: 'Feline Panleukopenia',                category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-fip',                    name: 'Feline Infectious Peritonitis (FIP)', category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-fiv',                    name: 'Feline Immunodeficiency Virus (FIV)', category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-heartworm-inf',          name: 'Heartworm Disease (Infectious)',       category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-helicobacter',           name: 'Helicobacter Infection',              category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-hemoplasmosis',          name: 'Hemoplasmosis (Mycoplasma haemofelis / haemocanis)', category: 'Infectious', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-histoplasmosis',         name: 'Histoplasmosis (Systemic)',            category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-leishmaniasis',          name: 'Leishmaniasis',                        category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-leptospirosis',          name: 'Leptospirosis',                        category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-lyme-disease',           name: 'Lyme Disease (Borreliosis)',           category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-mrsa',                   name: 'MRSA / MRSP (Methicillin-Resistant)',  category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-mycobacteriosis',        name: 'Mycobacteriosis',                      category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-nocardiosis',            name: 'Nocardiosis',                          category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-parvo',                  name: 'Parvovirus (Canine)',                  category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-pythiosis-inf',          name: 'Pythiosis (Systemic)',                 category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-rabies',                 name: 'Rabies',                               category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-ringworm-inf',           name: 'Ringworm / Dermatophytosis (Infectious)', category: 'Infectious',      species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-rmsf',                   name: 'Rocky Mountain Spotted Fever',         category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-salmonellosis',          name: 'Salmonellosis',                        category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-sporotrichosis',         name: 'Sporotrichosis',                       category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'inf-tetanus',                name: 'Tetanus',                              category: 'Infectious',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'inf-toxoplasmosis',          name: 'Toxoplasmosis',                        category: 'Infectious',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'inf-trypanosomiasis',        name: 'Trypanosomiasis',                      category: 'Infectious',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── ONCOLOGY (~35) ───────────────────────────────────────────────────────
  { id: 'onc-adrenal-carcinoma',      name: 'Adrenal Carcinoma',                   category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-all',                    name: 'Acute Lymphoblastic Leukemia (ALL)',   category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-apocrine-anal-sac',      name: 'Apocrine Gland Adenocarcinoma (Anal Sac)', category: 'Oncology',      species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'onc-basal-cell-tumor',       name: 'Basal Cell Tumor',                    category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-cll',                    name: 'Chronic Lymphocytic Leukemia (CLL)',  category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-fibrosarcoma-vass',      name: 'Vaccine-Associated Fibrosarcoma',     category: 'Oncology',            species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'onc-glioma',                 name: 'Glioma (Brain)',                       category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-hcc',                    name: 'Hepatocellular Carcinoma',             category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-hemangiosarcoma',        name: 'Hemangiosarcoma (Splenic / Hepatic / Cutaneous)', category: 'Oncology', species: ['dog'],       hasSeverity: false, severityScale: null },
  { id: 'onc-histiocytic-sarcoma',    name: 'Histiocytic Sarcoma',                 category: 'Oncology',            species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'onc-injection-site-sarcoma', name: 'Injection-Site Sarcoma',              category: 'Oncology',            species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'onc-insulinoma-onc',         name: 'Insulinoma (Pancreatic)',              category: 'Oncology',            species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'onc-lipoma-infiltrative',    name: 'Lipoma (Infiltrative)',               category: 'Oncology',            species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'onc-lymphoma',               name: 'Lymphoma (Multicentric / Alimentary / Mediastinal / Cutaneous)', category: 'Oncology', species: ['dog', 'cat'], hasSeverity: true, severityScale: 'tnm' },
  { id: 'onc-mammary-tumor',          name: 'Mammary Gland Tumor',                 category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-mast-cell-tumor',        name: 'Mast Cell Tumor',                     category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'grade-1-3' },
  { id: 'onc-melanoma',               name: 'Melanoma (Oral / Cutaneous / Digital)', category: 'Oncology',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-meningioma',             name: 'Meningioma',                           category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-multiple-myeloma',       name: 'Multiple Myeloma',                    category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-nasal-adenocarcinoma',   name: 'Nasal Adenocarcinoma',                category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-osteosarcoma-onc',       name: 'Osteosarcoma (Appendicular)',          category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-perianal-adenoma',       name: 'Perianal Adenoma / Adenocarcinoma',   category: 'Oncology',            species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'onc-pituitary-adenoma',      name: 'Pituitary Adenoma / Macroadenoma',    category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-plasmacytoma',           name: 'Plasmacytoma (Cutaneous / Extramedullary)', category: 'Oncology',     species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-pulmonary-carcinoma',    name: 'Pulmonary Carcinoma',                 category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-scc',                    name: 'Squamous Cell Carcinoma (Oral / Cutaneous / Nasal / Digital)', category: 'Oncology', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-sebaceous-tumor',        name: 'Sebaceous Gland Tumor',               category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-soft-tissue-sarcoma',    name: 'Soft Tissue Sarcoma (Unspecified)',   category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'grade-1-3' },
  { id: 'onc-splenic-mass',           name: 'Splenic Mass (Unspecified)',           category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-thymoma',                name: 'Thymoma',                              category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-thyroid-carcinoma-onc',  name: 'Thyroid Carcinoma (Oncology)',        category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-trichoblastoma',         name: 'Trichoblastoma',                       category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'onc-tcc-onc',                name: 'Transitional Cell Carcinoma (TCC)',    category: 'Oncology',            species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── OPHTHALMOLOGY (~30) ──────────────────────────────────────────────────
  { id: 'oph-cataracts',              name: 'Cataracts (Incipient / Immature / Mature / Hypermature)', category: 'Ophthalmology', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-cherry-eye',             name: 'Cherry Eye (Prolapsed Nictitans Gland)', category: 'Ophthalmology',  species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'oph-coloboma',               name: 'Coloboma',                             category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-conjunctivitis',         name: 'Conjunctivitis (Bacterial / Viral / Allergic)', category: 'Ophthalmology', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-corneal-degeneration',   name: 'Corneal Degeneration',                category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-corneal-dystrophy',      name: 'Corneal Dystrophy',                   category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-corneal-sequestrum',     name: 'Corneal Sequestrum',                  category: 'Ophthalmology',       species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'oph-corneal-ulcer',          name: 'Corneal Ulcer (Superficial / Deep / Descemetocele / Melting)', category: 'Ophthalmology', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-distichiasis',           name: 'Distichiasis',                         category: 'Ophthalmology',       species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'oph-ectopic-cilia',          name: 'Ectopic Cilia',                        category: 'Ophthalmology',       species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'oph-ectropion',              name: 'Ectropion',                            category: 'Ophthalmology',       species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'oph-entropion',              name: 'Entropion',                            category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-epiphora',               name: 'Epiphora (Excessive Tearing)',         category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-glaucoma',               name: 'Glaucoma (Primary / Secondary)',       category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: true,  severityScale: 'severity-1-5' },
  { id: 'oph-horner',                 name: "Horner Syndrome",                      category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-hypertensive-retino',    name: 'Hypertensive Retinopathy',            category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-hyphema',                name: 'Hyphema',                              category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-iris-melanoma',          name: 'Iris Melanoma',                        category: 'Ophthalmology',       species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'oph-kcs',                    name: 'Keratoconjunctivitis Sicca (KCS / Dry Eye)', category: 'Ophthalmology', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-lens-luxation',          name: 'Lens Luxation (Anterior / Posterior)', category: 'Ophthalmology',      species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-nasolacrimal-obstruct',  name: 'Nasolacrimal Duct Obstruction',       category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-optic-neuritis',         name: 'Optic Neuritis',                       category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-orbital-abscess',        name: 'Orbital Abscess / Cellulitis',        category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-pannus',                 name: 'Pannus (Chronic Superficial Keratitis)', category: 'Ophthalmology',    species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'oph-pra',                    name: 'Progressive Retinal Atrophy (PRA)',   category: 'Ophthalmology',       species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'oph-proptosis',              name: 'Proptosis (Globe Prolapse)',            category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-retinal-detachment',     name: 'Retinal Detachment',                  category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-sards',                  name: 'Sudden Acquired Retinal Degeneration (SARDS)', category: 'Ophthalmology', species: ['dog'],    hasSeverity: false, severityScale: null },
  { id: 'oph-uveitis',                name: 'Uveitis (Anterior / Posterior)',       category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'oph-uveal-cyst',             name: 'Uveal Cyst',                          category: 'Ophthalmology',       species: ['dog', 'cat'], hasSeverity: false, severityScale: null },

  // ─── BEHAVIORAL (~25) ─────────────────────────────────────────────────────
  { id: 'beh-acral-lick-beh',         name: 'Acral Lick Dermatitis (Behavioral)',  category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-aggression-fear',        name: 'Aggression (Fear / Territorial / Possessive)', category: 'Behavioral',  species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-attention-seeking',      name: 'Attention-Seeking Behavior',          category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-cds',                    name: 'Cognitive Dysfunction Syndrome (CDS / Canine Dementia)', category: 'Behavioral', species: ['dog'], hasSeverity: false, severityScale: null },
  { id: 'beh-compulsive',             name: 'Compulsive Disorder (Tail Chasing / Fly Biting / Shadow Chasing)', category: 'Behavioral', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-coprophagia',            name: 'Coprophagia',                          category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-displacement',           name: 'Displacement Behavior',               category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-env-stress',             name: 'Environmental Stress Syndrome',       category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-excessive-vocaliz',      name: 'Excessive Vocalization',              category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-feline-hyperesthesia',   name: 'Feline Hyperesthesia Syndrome',       category: 'Behavioral',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'beh-generalized-anxiety',    name: 'Generalized Anxiety',                 category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-hyperactivity',          name: 'Hyperactivity',                        category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-inappropriate-elim',     name: 'Inappropriate Elimination',           category: 'Behavioral',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'beh-intercat-aggression',    name: 'Inter-Cat Aggression',                category: 'Behavioral',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'beh-interdog-aggression',    name: 'Inter-Dog Aggression',                category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-leash-reactivity',       name: 'Leash Reactivity',                    category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-maternal-aggression',    name: 'Maternal Aggression',                 category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-noise-phobia',           name: 'Noise Phobia / Thunderstorm Anxiety', category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-phobic-disorder',        name: 'Phobic Disorder (Unspecified)',        category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-pica',                   name: 'Pica',                                 category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-predatory-aggression',   name: 'Predatory Aggression',                category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-psychogenic-alopecia',   name: 'Psychogenic Alopecia',                category: 'Behavioral',          species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'beh-resource-guarding',      name: 'Resource Guarding',                   category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-separation-anxiety',     name: 'Separation Anxiety',                  category: 'Behavioral',          species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'beh-sleep-disturbance',      name: 'Sleep Disturbance',                   category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-urine-marking',          name: 'Urine Marking',                       category: 'Behavioral',          species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'beh-wool-sucking',           name: 'Wool Sucking / Fabric Chewing',       category: 'Behavioral',          species: ['cat'],        hasSeverity: false, severityScale: null },

  // ─── PREVENTIVE / WELLNESS (~25) ──────────────────────────────────────────
  { id: 'prev-annual-wellness',       name: 'Annual Wellness Exam',                category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-behavioral-consult',    name: 'Behavioral Consultation',             category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-castration',            name: 'Neuter (Castration)',                  category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-cohat',                 name: 'Dental Prophylaxis (COHAT / Prophy)', category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-euthanasia-consult',    name: 'Euthanasia Consultation',             category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-export-cert',           name: 'Export / Import Health Certificate',  category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-geriatric-screen',      name: 'Geriatric Screening Panel',           category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-hospice',               name: 'Hospice Assessment',                  category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-kitten-wellness',       name: 'Kitten Wellness Exam',                category: 'Preventive / Wellness', species: ['cat'],        hasSeverity: false, severityScale: null },
  { id: 'prev-microchip',             name: 'Microchip Placement',                 category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-neonatal',              name: 'Neonatal Exam',                        category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-nutrition-consult',     name: 'Nutrition Consultation',              category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-ohx',                   name: 'Spay (Ovariohysterectomy)',            category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-palliative',            name: 'Palliative Care Consultation',        category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-parasite-prevention',   name: 'Parasite Prevention Counseling',      category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-postop-recheck',        name: 'Post-Operative Recheck',              category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-prebreeding',           name: 'Pre-Breeding Evaluation',             category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-presurgical',           name: 'Pre-Surgical Screening',              category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-pregnancy-check',       name: 'Pregnancy Check',                     category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-puppy-wellness',        name: 'Puppy Wellness Exam',                 category: 'Preventive / Wellness', species: ['dog'],        hasSeverity: false, severityScale: null },
  { id: 'prev-recheck',               name: 'Recheck / Follow-Up Visit',           category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-second-opinion',        name: 'Second Opinion Evaluation',           category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-senior-wellness',       name: 'Senior Wellness Exam',                category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-travel-cert',           name: 'Travel Health Certificate',           category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-vaccination-visit',     name: 'Vaccination Visit',                   category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
  { id: 'prev-weight-management',     name: 'Weight Management Program',           category: 'Preventive / Wellness', species: ['dog', 'cat'], hasSeverity: false, severityScale: null },
];
