/**
 * labTestConstants.js
 * T4.120 — Lab Results System Redesign (Day 1)
 *
 * Hardcoded catalog of ~78 veterinary lab tests across 9 categories.
 * Each entry is the canonical definition shared by the form, display,
 * and AI prompt builders — a single source of truth for names, units,
 * and species-specific reference ranges.
 *
 * resultType:
 *   'numeric'          — has a measurable numeric value; auto-status from reference range
 *   'positive-negative' — qualitative; positive→'abnormal', negative→'normal' (Amendment 1)
 *   'descriptive'      — free-text interpretation; no auto-status
 *
 * referenceRange shape: { canine: [low, high], feline: [low, high] }
 * Tests without meaningful reference ranges (e.g. descriptive) use null.
 */

export const LAB_CATEGORIES = [
  'Hematology',
  'Chemistry',
  'SNAP Tests',
  'Urinalysis',
  'Fecal',
  'Cytology',
  'Endocrine',
  'Coagulation',
  'Other',
];

/** All 3 values used across all consumers for chip color mapping. */
export const LAB_STATUSES = ['normal', 'abnormal', 'critical'];

export const DEFAULT_LAB_TEST_CATALOG = [
  // ─── HEMATOLOGY (10) ─────────────────────────────────────────────────────────
  {
    id: 'cbc-rbc',
    name: 'RBC (Red Blood Cells)',
    category: 'Hematology',
    unit: '×10¹²/L',
    referenceRange: { canine: [5.5, 8.5], feline: [5.0, 10.0] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-wbc',
    name: 'WBC (White Blood Cells)',
    category: 'Hematology',
    unit: '×10⁹/L',
    referenceRange: { canine: [6.0, 17.0], feline: [5.5, 19.5] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-hct',
    name: 'PCV / HCT (Packed Cell Volume)',
    category: 'Hematology',
    unit: '%',
    referenceRange: { canine: [37, 55], feline: [24, 45] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-hgb',
    name: 'Hemoglobin',
    category: 'Hematology',
    unit: 'g/dL',
    referenceRange: { canine: [12, 18], feline: [8, 15] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-plt',
    name: 'Platelets',
    category: 'Hematology',
    unit: '×10⁹/L',
    referenceRange: { canine: [200, 500], feline: [300, 700] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-mcv',
    name: 'MCV (Mean Corpuscular Volume)',
    category: 'Hematology',
    unit: 'fL',
    referenceRange: { canine: [62, 72], feline: [39, 55] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-mch',
    name: 'MCH (Mean Corpuscular Hemoglobin)',
    category: 'Hematology',
    unit: 'pg',
    referenceRange: { canine: [20, 25], feline: [12, 17] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-mchc',
    name: 'MCHC (Mean Corpuscular Hemoglobin Concentration)',
    category: 'Hematology',
    unit: 'g/dL',
    referenceRange: { canine: [32, 36], feline: [30, 36] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-neut',
    name: 'Neutrophils (Segmented)',
    category: 'Hematology',
    unit: '×10⁹/L',
    referenceRange: { canine: [3.0, 11.5], feline: [2.5, 12.5] },
    resultType: 'numeric',
  },
  {
    id: 'cbc-lymph',
    name: 'Lymphocytes',
    category: 'Hematology',
    unit: '×10⁹/L',
    referenceRange: { canine: [1.0, 4.8], feline: [1.5, 7.0] },
    resultType: 'numeric',
  },

  // ─── CHEMISTRY (22) ──────────────────────────────────────────────────────────
  {
    id: 'chem-alt',
    name: 'ALT / SGPT (Alanine Aminotransferase)',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [10, 100], feline: [10, 100] },
    resultType: 'numeric',
  },
  {
    id: 'chem-ast',
    name: 'AST / SGOT (Aspartate Aminotransferase)',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [15, 50], feline: [15, 50] },
    resultType: 'numeric',
  },
  {
    id: 'chem-alp',
    name: 'ALP (Alkaline Phosphatase)',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [20, 150], feline: [10, 90] },
    resultType: 'numeric',
  },
  {
    id: 'chem-bun',
    name: 'BUN (Blood Urea Nitrogen)',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [9, 29], feline: [18, 36] },
    resultType: 'numeric',
  },
  {
    id: 'chem-creat',
    name: 'Creatinine',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [0.5, 1.5], feline: [0.8, 1.8] },
    resultType: 'numeric',
  },
  {
    id: 'chem-gluc',
    name: 'Glucose',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [70, 143], feline: [65, 130] },
    resultType: 'numeric',
  },
  {
    id: 'chem-tp',
    name: 'Total Protein',
    category: 'Chemistry',
    unit: 'g/dL',
    referenceRange: { canine: [5.5, 7.5], feline: [6.0, 8.0] },
    resultType: 'numeric',
  },
  {
    id: 'chem-alb',
    name: 'Albumin',
    category: 'Chemistry',
    unit: 'g/dL',
    referenceRange: { canine: [2.3, 3.9], feline: [2.1, 3.3] },
    resultType: 'numeric',
  },
  {
    id: 'chem-glob',
    name: 'Globulin',
    category: 'Chemistry',
    unit: 'g/dL',
    referenceRange: { canine: [2.3, 4.0], feline: [2.8, 5.1] },
    resultType: 'numeric',
  },
  {
    id: 'chem-tbili',
    name: 'Total Bilirubin',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [0.0, 0.4], feline: [0.0, 0.4] },
    resultType: 'numeric',
  },
  {
    id: 'chem-dbili',
    name: 'Direct Bilirubin',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [0.0, 0.1], feline: [0.0, 0.1] },
    resultType: 'numeric',
  },
  {
    id: 'chem-chol',
    name: 'Cholesterol',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [110, 320], feline: [75, 220] },
    resultType: 'numeric',
  },
  {
    id: 'chem-trig',
    name: 'Triglycerides',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [25, 150], feline: [25, 150] },
    resultType: 'numeric',
  },
  {
    id: 'chem-amyl',
    name: 'Amylase',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [200, 1200], feline: [500, 1500] },
    resultType: 'numeric',
  },
  {
    id: 'chem-lip',
    name: 'Lipase',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [0, 200], feline: [0, 200] },
    resultType: 'numeric',
  },
  {
    id: 'chem-ca',
    name: 'Calcium',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [8.9, 11.4], feline: [8.8, 11.9] },
    resultType: 'numeric',
  },
  {
    id: 'chem-phos',
    name: 'Phosphorus',
    category: 'Chemistry',
    unit: 'mg/dL',
    referenceRange: { canine: [2.9, 6.2], feline: [3.0, 7.0] },
    resultType: 'numeric',
  },
  {
    id: 'chem-na',
    name: 'Sodium',
    category: 'Chemistry',
    unit: 'mEq/L',
    referenceRange: { canine: [141, 152], feline: [147, 157] },
    resultType: 'numeric',
  },
  {
    id: 'chem-k',
    name: 'Potassium',
    category: 'Chemistry',
    unit: 'mEq/L',
    referenceRange: { canine: [3.8, 5.0], feline: [3.4, 5.6] },
    resultType: 'numeric',
  },
  {
    id: 'chem-cl',
    name: 'Chloride',
    category: 'Chemistry',
    unit: 'mEq/L',
    referenceRange: { canine: [102, 117], feline: [107, 123] },
    resultType: 'numeric',
  },
  {
    id: 'chem-ggt',
    name: 'GGT (Gamma-Glutamyl Transferase)',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [0, 11], feline: [0, 8] },
    resultType: 'numeric',
  },
  {
    id: 'chem-ck',
    name: 'CK / CPK (Creatine Kinase)',
    category: 'Chemistry',
    unit: 'U/L',
    referenceRange: { canine: [10, 200], feline: [56, 529] },
    resultType: 'numeric',
  },

  // ─── SNAP TESTS (11) ─────────────────────────────────────────────────────────
  {
    id: 'snap-4dx',
    name: 'SNAP 4Dx Plus (Heartworm/Lyme/Ehrlichia/Anaplasma)',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-hw',
    name: 'SNAP Heartworm Antigen',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-fiv-felv',
    name: 'SNAP FIV/FeLV Combo',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-parvo',
    name: 'SNAP Parvo Antigen',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-cpl',
    name: 'SNAP cPL (Canine Pancreatic Lipase)',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-fpl',
    name: 'SNAP fPL (Feline Pancreatic Lipase)',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-t4',
    name: 'SNAP T4 / Thyroid',
    category: 'SNAP Tests',
    unit: 'µg/dL',
    referenceRange: { canine: [1.0, 4.0], feline: [0.8, 4.0] },
    resultType: 'numeric',
  },
  {
    id: 'snap-prog',
    name: 'SNAP Progesterone',
    category: 'SNAP Tests',
    unit: 'ng/mL',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'snap-cort',
    name: 'SNAP Cortisol',
    category: 'SNAP Tests',
    unit: 'µg/dL',
    referenceRange: { canine: [1.0, 6.0], feline: [1.0, 5.0] },
    resultType: 'numeric',
  },
  {
    id: 'snap-giardia',
    name: 'SNAP Giardia Antigen',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'snap-leish',
    name: 'SNAP Leishmania Antibody',
    category: 'SNAP Tests',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },

  // ─── URINALYSIS (10) ─────────────────────────────────────────────────────────
  {
    id: 'ua-sg',
    name: 'Specific Gravity',
    category: 'Urinalysis',
    unit: '',
    referenceRange: { canine: [1.015, 1.045], feline: [1.020, 1.060] },
    resultType: 'numeric',
  },
  {
    id: 'ua-ph',
    name: 'Urine pH',
    category: 'Urinalysis',
    unit: '',
    referenceRange: { canine: [6.0, 7.5], feline: [6.0, 7.5] },
    resultType: 'numeric',
  },
  {
    id: 'ua-prot',
    name: 'Urine Protein',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'ua-gluc',
    name: 'Urine Glucose',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'ua-bili',
    name: 'Urine Bilirubin',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'ua-blood',
    name: 'Urine Blood / Hemoglobin',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'ua-wbc',
    name: 'Urine WBC (Pyuria)',
    category: 'Urinalysis',
    unit: 'cells/hpf',
    referenceRange: { canine: [0, 5], feline: [0, 5] },
    resultType: 'numeric',
  },
  {
    id: 'ua-bact',
    name: 'Urine Bacteria',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'ua-casts',
    name: 'Urine Casts',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'ua-crystals',
    name: 'Urine Crystals',
    category: 'Urinalysis',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },

  // ─── FECAL (4) ───────────────────────────────────────────────────────────────
  {
    id: 'fecal-float',
    name: 'Fecal Float (Flotation)',
    category: 'Fecal',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'fecal-direct',
    name: 'Fecal Direct Smear',
    category: 'Fecal',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'fecal-giardia',
    name: 'Giardia Antigen (Fecal)',
    category: 'Fecal',
    unit: '',
    referenceRange: null,
    resultType: 'positive-negative',
  },
  {
    id: 'fecal-culture',
    name: 'Fecal Culture',
    category: 'Fecal',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },

  // ─── CYTOLOGY (5) ────────────────────────────────────────────────────────────
  {
    id: 'cyto-skin',
    name: 'Skin Scraping',
    category: 'Cytology',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'cyto-ear',
    name: 'Ear Cytology',
    category: 'Cytology',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'cyto-fna',
    name: 'FNA (Fine Needle Aspirate)',
    category: 'Cytology',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'cyto-impression',
    name: 'Impression Smear',
    category: 'Cytology',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'cyto-joint',
    name: 'Joint Fluid Analysis',
    category: 'Cytology',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },

  // ─── ENDOCRINE (7) ───────────────────────────────────────────────────────────
  {
    id: 'endo-t4',
    name: 'Total T4 (Thyroxine)',
    category: 'Endocrine',
    unit: 'µg/dL',
    referenceRange: { canine: [1.0, 4.0], feline: [0.8, 4.0] },
    resultType: 'numeric',
  },
  {
    id: 'endo-ft4',
    name: 'Free T4 (fT4 by ED)',
    category: 'Endocrine',
    unit: 'ng/dL',
    referenceRange: { canine: [0.8, 3.5], feline: [0.7, 2.5] },
    resultType: 'numeric',
  },
  {
    id: 'endo-tsh',
    name: 'TSH (Thyroid Stimulating Hormone)',
    category: 'Endocrine',
    unit: 'ng/mL',
    referenceRange: { canine: [0.0, 0.6], feline: [0.0, 0.4] },
    resultType: 'numeric',
  },
  {
    id: 'endo-cort-base',
    name: 'Cortisol (Baseline)',
    category: 'Endocrine',
    unit: 'µg/dL',
    referenceRange: { canine: [1.0, 6.0], feline: [1.0, 5.0] },
    resultType: 'numeric',
  },
  {
    id: 'endo-acth',
    name: 'ACTH Stimulation Test',
    category: 'Endocrine',
    unit: 'µg/dL',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'endo-lddst',
    name: 'Low-Dose Dexamethasone Suppression',
    category: 'Endocrine',
    unit: 'µg/dL',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'endo-fructo',
    name: 'Fructosamine',
    category: 'Endocrine',
    unit: 'µmol/L',
    referenceRange: { canine: [225, 365], feline: [190, 365] },
    resultType: 'numeric',
  },

  // ─── COAGULATION (4) ─────────────────────────────────────────────────────────
  {
    id: 'coag-pt',
    name: 'PT (Prothrombin Time)',
    category: 'Coagulation',
    unit: 'seconds',
    referenceRange: { canine: [6.0, 9.0], feline: [7.0, 10.5] },
    resultType: 'numeric',
  },
  {
    id: 'coag-aptt',
    name: 'aPTT (Activated Partial Thromboplastin Time)',
    category: 'Coagulation',
    unit: 'seconds',
    referenceRange: { canine: [8.0, 13.5], feline: [8.0, 13.0] },
    resultType: 'numeric',
  },
  {
    id: 'coag-fibrin',
    name: 'Fibrinogen',
    category: 'Coagulation',
    unit: 'mg/dL',
    referenceRange: { canine: [150, 400], feline: [100, 300] },
    resultType: 'numeric',
  },
  {
    id: 'coag-ddimer',
    name: 'D-dimer',
    category: 'Coagulation',
    unit: 'µg/mL',
    referenceRange: { canine: [0, 0.25], feline: [0, 0.25] },
    resultType: 'numeric',
  },

  // ─── OTHER (5) ───────────────────────────────────────────────────────────────
  {
    id: 'other-blood-gas-ph',
    name: 'Blood Gas (pH)',
    category: 'Other',
    unit: '',
    referenceRange: { canine: [7.36, 7.44], feline: [7.36, 7.44] },
    resultType: 'numeric',
  },
  {
    id: 'other-lactate',
    name: 'Lactate',
    category: 'Other',
    unit: 'mmol/L',
    referenceRange: { canine: [0.5, 2.5], feline: [0.5, 2.5] },
    resultType: 'numeric',
  },
  {
    id: 'other-blood-smear',
    name: 'Blood Smear Evaluation',
    category: 'Other',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'other-electrophoresis',
    name: 'Protein Electrophoresis',
    category: 'Other',
    unit: '',
    referenceRange: null,
    resultType: 'descriptive',
  },
  {
    id: 'other-bile-acids',
    name: 'Bile Acids',
    category: 'Other',
    unit: 'µmol/L',
    referenceRange: { canine: [0, 25], feline: [0, 15] },
    resultType: 'numeric',
  },
];
