import { PRINT_STYLES, esc, openPrintWindow } from './printUtils';

/**
 * Generates a self-contained printable HTML string for the clinic's
 * inventory reorder list — all non-archived items currently at or below
 * their minStock threshold.
 *
 * Items are sorted by deficit descending (most urgent first), so the
 * person placing the supplier order can prioritise.
 *
 * @param {Array}  lowStockItems   Pre-filtered array of inventory items below threshold
 * @param {object} clinicSettings  Firestore clinic_settings/general document data
 * @returns {string} Full HTML document string
 */
export function generateReorderListHTML(lowStockItems, clinicSettings = {}) {
  const clinicName = esc(clinicSettings?.clinicName || 'Starbarks Veterinary Clinic');
  const clinicAddr = esc(clinicSettings?.clinicAddress || '');
  const generated = new Date().toLocaleString('en-PH', {
    timeZone: 'Asia/Manila',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Sort by deficit descending — items furthest below threshold appear first
  const sorted = [...lowStockItems].sort((a, b) => {
    const deficitA = (Number(a.minStock) || 10) - (Number(a.stock) || 0);
    const deficitB = (Number(b.minStock) || 10) - (Number(b.stock) || 0);
    return deficitB - deficitA;
  });

  const rows = sorted.map((item) => {
    const stock = Number(item.stock) || 0;
    const min = Number(item.minStock) || 10;
    const deficit = min - stock;
    const isOutOfStock = stock <= 0;

    const stockCell = isOutOfStock
      ? `<strong style="color:#D32F2F;">OUT OF STOCK</strong>`
      : `<span style="color:#E65100;font-weight:700;">${stock}</span>`;

    return `<tr>
      <td>${esc(item.itemName || '—')}</td>
      <td>${esc(item.sku || '—')}</td>
      <td>${esc(item.category ? item.category.charAt(0).toUpperCase() + item.category.slice(1).toLowerCase() : '—')}</td>
      <td style="text-align:center">${stockCell}</td>
      <td style="text-align:center">${min}</td>
      <td style="text-align:center;font-weight:900;color:#D32F2F">${deficit}</td>
      <td>${esc(item.supplier || '—')}</td>
      <td style="text-align:center">${esc(item.unit || '—')}</td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Inventory Reorder List</title>
  <style>
    ${PRINT_STYLES}
    .summary-line {
      text-align: center;
      font-size: 13px;
      font-weight: 700;
      color: #D32F2F;
      margin-bottom: 16px;
    }
  </style>
</head>
<body>
  <div class="clinic-header">
    <p class="clinic-name">${clinicName}</p>
    ${clinicAddr ? `<p class="clinic-address">${clinicAddr}</p>` : ''}
    ${clinicSettings?.clinicPhone ? `<p class="clinic-address">TEL: ${esc(clinicSettings.clinicPhone)}</p>` : ''}
    ${clinicSettings?.clinicTIN ? `<p class="clinic-address">TIN: ${esc(clinicSettings.clinicTIN)}</p>` : ''}
  </div>
  <div class="doc-title">INVENTORY REORDER LIST</div>
  <p style="text-align:center;font-size:11px;color:#A1887F;">Generated: ${generated}</p>
  <p class="summary-line">${sorted.length} item${sorted.length !== 1 ? 's' : ''} below reorder threshold</p>
  <table>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>SKU</th>
        <th>Category</th>
        <th style="text-align:center">Current Stock</th>
        <th style="text-align:center">Min Stock</th>
        <th style="text-align:center">Deficit</th>
        <th>Supplier</th>
        <th style="text-align:center">Unit</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <div class="footer">Generated by VetConnect Inventory System &bull; ${clinicName}</div>
</body>
</html>`;
}

/**
 * Opens a print window containing the reorder list report.
 * Calls `onBlocked` if the browser's popup blocker prevents the window.
 *
 * @param {Array}    lowStockItems   Pre-filtered inventory items below threshold
 * @param {object}   clinicSettings  Firestore clinic_settings/general document data
 * @param {function} [onBlocked]     Callback invoked when the popup is blocked
 */
export function printReorderList(lowStockItems, clinicSettings, onBlocked) {
  const html = generateReorderListHTML(lowStockItems, clinicSettings);
  openPrintWindow(html, onBlocked);
}
